# Generated by Django 5.0.6 on 2024-05-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='filiere',
            field=models.CharField(blank=True, choices=[('math', 'Mathématiques'), ('sci', 'Sciences'), ('let', 'Lettres')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(blank=True, choices=[('sports', 'Sports'), ('music', 'Musique'), ('reading', 'Lecture'), ('travel', 'Voyages'), ('others', 'Autres')], max_length=500, null=True),
        ),
    ]
