# Generated by Django 5.0.6 on 2024-06-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestUsers', '0002_alter_profile_filiere_alter_profile_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='academic_interests',
            field=models.CharField(blank=True, choices=[('Sciences', 'Sciences'), ('Arts', 'Arts'), ('Affaires', 'Affaires'), ('Autre', 'Autre')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cleanliness',
            field=models.CharField(blank=True, choices=[('Très organisé(e)', 'Très organisé(e)'), ('Tolérant(e) envers le désordre', 'Tolérant(e) envers le désordre')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='common_area_usage',
            field=models.CharField(blank=True, choices=[('Utilisation fréquente des espaces communs', 'Utilisation fréquente des espaces communs'), ('Utilisation occasionnelle des espaces communs', 'Utilisation occasionnelle des espaces communs')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='consumption_habits',
            field=models.CharField(blank=True, choices=[('Fumeur(se)', 'Fumeur(se)'), ('Non fumeur(se)', 'Non fumeur(se)'), ('Buveur(se) occasionnel(le)', 'Buveur(se) occasionnel(le)'), ('Non buveur(se)', 'Non buveur(se)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifestyle',
            field=models.CharField(blank=True, choices=[('Du matin', 'Du matin'), ('Du soir', 'Du soir')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meal_preferences',
            field=models.CharField(blank=True, choices=[('Végétalien(ne)', 'Végétalien(ne)'), ('Végétarien(ne)', 'Végétarien(ne)'), ('Sans gluten', 'Sans gluten'), ('Aucune préférence particulière', 'Aucune préférence particulière')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nightlife',
            field=models.CharField(blank=True, choices=[('Noctambule', 'Noctambule'), ('Soirées calmes à la maison', 'Soirées calmes à la maison')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_level_tolerance',
            field=models.CharField(blank=True, choices=[('Sensible au bruit', 'Sensible au bruit'), ('Tolérant(e) envers le bruit', 'Tolérant(e) envers le bruit')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pet_friendly',
            field=models.CharField(blank=True, choices=[('Allergique aux animaux', 'Allergique aux animaux'), ('Amateur(trice) danimaux de compagnie', 'Amateur(trice) danimaux de compagnie'), ('Neutre', 'Neutre')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_interaction_preference',
            field=models.CharField(blank=True, choices=[('Interactions sociales fréquentes', 'Interactions sociales fréquentes'), ('Préférence pour lindépendance', 'Préférence pour lindépendance')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='filiere',
            field=models.CharField(blank=True, choices=[('Mathématiques', 'Mathématiques'), ('Sciences', 'Sciences'), ('Lettres', 'Lettres')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(blank=True, choices=[('Sports', 'Sports'), ('Musique', 'Musique'), ('Lecture', 'Lecture'), ('Voyages', 'Voyages'), ('Autres', 'Autres')], max_length=500, null=True),
        ),
    ]
