# Generated by Django 5.0.6 on 2024-06-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestAnnounce', '0002_housingapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housing',
            old_name='photo',
            new_name='photo_url',
        ),
    ]
