# Generated by Django 5.0.6 on 2024-06-16 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestAnnounce', '0003_rename_photo_housing_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housing',
            old_name='photo_url',
            new_name='photo',
        ),
    ]
